In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

### Read the set of labels into a dataframe:

In [2]:
labels = pd.read_csv('labels.csv')

In [3]:
labels.head()

perfect_labeler radiologist  algorithm
0          cancer      cancer       0.99
1          cancer      cancer       0.94
2          cancer      cancer       0.73
3          cancer      cancer       0.82
4          cancer      cancer       0.98

### Start with assessing the radiologist's performance:
* Assess the _accuracy_ of the radiologist by just looking at the percent of cases that they correctly labeled
* Next, look at the true positive and true negative rates of the radiologist by generating a _confusion matrix_ 

In [4]:
radiologist_accuracy = sum(labels.perfect_labeler == labels.radiologist)/len(labels)

In [5]:
radiologist_accuracy

0.8993288590604027

In [6]:
confusion_matrix(labels.perfect_labeler.values,labels.radiologist.values,labels=["cancer","benign"])

array([[ 25,   4],
       [ 11, 109]])

### Now look at the algorithm's performance compared to the perfect labeler:
* Since the algorithm doesn't create a binary label, it instead returns a _probability_ of cancer, choose a probability cut-off to use for the algorithm's labeling of cancer vs. bening. _(Hint: 0.5 is a reasonable starting place)_
* Start with assessing _accuracy_ again here
* Generate a confusion matrix

In [7]:
cutoff = labels[labels['algorithm'] > 0.5]

In [8]:
radiologist_accuracy = sum(cutoff.perfect_labeler == cutoff.radiologist)/len(cutoff)
radiologist_accuracy

0.7931034482758621

In [9]:
confusion_matrix(cutoff.perfect_labeler.values,cutoff.radiologist.values,labels=["cancer","benign"])

array([[19,  2],
       [ 4,  4]])

What happens now if you change the threshold cut-off for your algorithm's classification to 0.4? What if you raise it to 0.6? How do accuracy, fp, fn, tp, and tn change?

In [10]:
cutoff2 = labels[labels['algorithm'] > 0.4]
radiologist_accuracy = sum(cutoff2.perfect_labeler == cutoff2.radiologist)/len(cutoff2)
radiologist_accuracy

0.8292682926829268

In [11]:
confusion_matrix(cutoff2.perfect_labeler.values,cutoff2.radiologist.values,labels=["cancer","benign"])

array([[22,  3],
       [ 4, 12]])

In [12]:
cutoff3 = labels[labels['algorithm'] > 0.6]
radiologist_accuracy = sum(cutoff3.perfect_labeler == cutoff3.radiologist)/len(cutoff3)
radiologist_accuracy

0.8

In [13]:
confusion_matrix(cutoff3.perfect_labeler.values,cutoff3.radiologist.values,labels=["cancer","benign"])

array([[18,  2],
       [ 3,  2]])

### Finally, let's compare our algorithm to the radiologist
* A "perfect labeler" might not exist in the real world, and in fact, if often does not
* In AI for medical imaging, using a radiologist's labels as our "true" label is often the standard of practice, and algorithm performance is judged in both an academic setting as well as in the regulated industry landscape based on performance against an expert human

* Repeat the steps above using a set threshold for your algorithm (again, 0.5 is perfectly reasonable) but now computing accuracy, tp, tn, fp, fn against the radiologist. 

In [16]:
def rounding(x):
    if x >= 0.5:
        return 'cancer'
    else:
        return 'benign'
    
cutoff = labels[labels['algorithm'] > 0.5]
cutoff['alg_guess'] = cutoff['algorithm'].apply(rounding)
cutoff

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


perfect_labeler radiologist  algorithm alg_guess
0            cancer      cancer       0.99    cancer
1            cancer      cancer       0.94    cancer
2            cancer      cancer       0.73    cancer
3            cancer      cancer       0.82    cancer
4            cancer      cancer       0.98    cancer
5            cancer      cancer       0.63    cancer
7            cancer      cancer       0.99    cancer
8            cancer      cancer       0.92    cancer
10           cancer      cancer       0.96    cancer
11           cancer      cancer       0.99    cancer
12           cancer      cancer       0.89    cancer
13           cancer      cancer       0.90    cancer
14           cancer      cancer       0.88    cancer
15           cancer      cancer       0.55    cancer
17           cancer      cancer       0.77    cancer
18           cancer      cancer       0.67    cancer
21           cancer      cancer       0.99    cancer
22           cancer      cancer       0.95    cancer
23           cancer      cancer       0.93    cancer
25           cancer      benign       0.67    cancer
28           cancer      benign       0.96    cancer
49           benign      benign       0.76    cancer
50           benign      benign       0.54    cancer
98           benign      benign       0.90    cancer
99           benign      benign       0.55    cancer
139          benign      cancer       0.57    cancer
143          benign      cancer       0.66    cancer
145          benign      cancer       0.98    cancer
146          benign      cancer       0.77    cancer

In [17]:
radiologist_accuracy = sum(cutoff.radiologist == cutoff.alg_guess)/len(cutoff)
radiologist_accuracy

0.7931034482758621

In [18]:
confusion_matrix(cutoff.alg_guess.values,cutoff.radiologist.values,labels=["cancer","benign"])

array([[23,  6],
       [ 0,  0]])

## Reflection: 
* In the above exercise you assess performances of a human as well as of an algorithm against a 'perfect labeler' and also against each other. 
* Does accuracy seem like the appropriate statistic to use when evaluating these labels? Why or why not? 
* In what clinical settings does it seem more or less acceptable to have a high level of FNs? FPs? 
* How did changing the threshold on the algorithm performance change the different performance statistics? 
* How did your opinion of the algorithm's performance change when you started comparing it to a radiologist instead of the perfect labeler? What does this mean for a real-world scenario when a perfect labeler doesn't exist, and we only have a radiologist's read to base our performance on? 